# Generated by Django 6.0.1 on 2026-01-19 10:08

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(editable=False, null=True)),
                ("updated", models.DateTimeField(editable=False, null=True)),
                (
                    "filename",
                    models.CharField(
                        blank=True,
                        help_text="Original filename",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of the file",
                        max_length=100,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=files.models.get_user_files_storage,
                        upload_to=files.models.Uploads(),
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
